website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   
from flask_login import login_user, login_required, logout_user, current_user

# Létrehozzuk az 'auth' Blueprint-ot.
auth = Blueprint('auth', __name__)


# Definiáljuk a bejelentkezési útvonalat és a hozzá tartozó függvényt.
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        # Ellenőrizzük, hogy létezik-e már ilyen email című felhasználó.
        user = User.query.filter_by(email=email).first()
        if user:
            # Ha a jelszó helyes és a felhasználó jóvá van hagyva, akkor bejelentkeztetjük a felhasználót.
            if check_password_hash(user.password, password) and user.is_approved:
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            elif not user.is_approved:
                flash('Your account is not approved yet. Please wait for approval.', category='error')
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


# Definiáljuk a kijelentkezési útvonalat és a hozzá tartozó függvényt.
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# Definiáljuk a regisztrációs útvonalat és a hozzá tartozó függvényt.
@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        second_name = request.form.get('secondName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(second_name) < 2:
            flash('Second name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, second_name=second_name, password=generate_password_hash(
                password1, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created! Please wait for admin approval before logging in.', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)


# Regsiztráció jóváhagyása
@auth.route('/approve_user/<int:user_id>', methods=['POST'])
@login_required
def approve_user(user_id):
    user = User.query.get(user_id)

    if user and not user.is_approved:
        user.is_approved = True
        db.session.commit()
        flash(f'User {user.email} has been approved.', category='success')

    return redirect(url_for('views.admin_dashboard'))

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, abort
from flask_login import login_required, current_user
from .models import Note, User, Investment, InvestmentSnapshot, Asset
from . import db
import json
from datetime import datetime
from functools import wraps
from sqlalchemy.exc import IntegrityError
import yfinance as yf

# Létrehozzuk a views Blueprint-et.
views = Blueprint('views', __name__)


# Definiáljuk a főoldal útvonalát.
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        note = request.form.get('note') 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  
            db.session.add(new_note)  
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)


# Definiáljuk a feljegyzés törlésének útvonalát.
@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


# Definiáljuk az összes felhasználót megjelenítő útvonalat.
@views.route('/all-users', methods=['GET'])
@login_required
def all_users():
    users = User.query.all()
    return render_template("all_users.html", users=users, user=current_user)


# Definiáljuk a felhasználó szerkesztésének útvonalát.
@views.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    if request.method == 'POST':
        user.email = request.form.get('email')
        user.first_name = request.form.get('firstName')
        user.second_name = request.form.get('secondName')
        db.session.commit()
        flash('User updated!', category='success')
        return redirect(url_for('views.all_users'))

    return render_template("edit_user.html", user=user)


# Definiáljuk a felhasználó törlésének útvonalát.
@views.route('/delete-user/<int:user_id>', methods=['GET'])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    try:
        db.session.commit()
        flash('User deleted!', category='success')
    except IntegrityError:
        db.session.rollback()
        flash('Integrity error!', category='error')

    return redirect(url_for('views.all_users'))


# Definiáljuk a befektetés létrehozásának útvonalát.
@views.route('/create-investment', methods=['GET', 'POST'])
@login_required
def create_investment():
    users = User.query.all()
    user_investments = Investment.query.all()
    assets = Asset.query.all()
    if request.method == 'POST':
        
        user_id = request.form.get('user')
        asset_id = request.form.get('asset')
        asset = Asset.query.get(asset_id)

        purchase_date = request.form.get('purchaseDate')
        purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d")
        purchase_price = request.form.get('purchasePrice')
        quantity = request.form.get('quantity')
        current_price = request.form.get('currentPrice')
        expected_interest_amount = request.form.get('expectedInterestAmount')

        new_investment = Investment(asset_id=asset.id, asset_name=asset.name, asset_type=asset.type, purchase_date=purchase_date, purchase_price=purchase_price, quantity=quantity, current_price=current_price, expected_interest_amount=expected_interest_amount, user_id=user_id)
        
        db.session.add(new_investment)
        db.session.commit()
        flash('Investment created!', category='success')
        return redirect(url_for('views.create_investment'))
    
    return render_template("create_investment.html", user_investments=user_investments, user=current_user, users=users, assets=assets)



# Definiáljuk a befektetés szerkesztésémek útvonalát.
@views.route('/edit-investment/<int:investment_id>', methods=['GET', 'POST'])
@login_required
def edit_investment(investment_id):
    investment = Investment.query.get_or_404(investment_id)
    users = User.query.all()
    assets = Asset.query.all()
    if request.method == 'POST':
    
        investment.asset_id = request.form.get('asset')
        
        purchase_date = request.form.get('purchaseDate')  
        purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d")
        investment.purchase_date = purchase_date  
        
        investment.purchase_price = float(request.form.get('purchasePrice'))
        investment.quantity = float(request.form.get('quantity'))
        investment.current_price = float(request.form.get('currentPrice'))
        investment.expected_interest_amount = float(request.form.get('expectedInterestAmount'))
        
        user_id = request.form.get('user') 
        investment.user_id = user_id  

        db.session.commit()
        flash('Investment updated!', category='success')
        return redirect(url_for('views.create_investment'))

    # Itt adjuk át az assets változót a sablonnak
    return render_template('edit_investment.html', investment=investment, user=current_user, users=users, assets=assets)  


# Definiáljuk a befektetés törlésének útvonalát.
@views.route('/delete-investment/<int:investment_id>', methods=['GET'])
@login_required
def delete_investment(investment_id):
    investment = Investment.query.get_or_404(investment_id)
    if investment.user_id == current_user.id:
        db.session.delete(investment)
        db.session.commit()
        flash('Investment deleted!', category='success')
    return redirect(url_for('views.create_investment'))

# Definiáljuk a jelszó ellenőrző függvényt
def check_password(password):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            error = None
            if request.method == 'POST':
                provided_password = request.form.get('password')
                if provided_password == password:
                    return f(*args, **kwargs)
                error = "Incorrect password. Please try again."
            return render_template('password_protected.html', user=current_user, error=error)
        return decorated_function
    return decorator


# Definiáljuk az admin_dashboard útvonalát.
@views.route('/admin_dashboard', methods=['GET', 'POST'])
@login_required
@check_password('123456')  # Replace 'your_password_here' with the desired password
def admin_dashboard():
    if request.method == 'POST':
        users = User.query.filter_by(is_approved=False).all()
        return render_template("admin_dashboard.html", user=current_user, users=users)
    users = User.query.filter_by(is_approved=False).all()
    return render_template("password_protected.html", user=current_user, users=users)

# Definiáljuk a snapshot útvonalát.
@views.route('/create_snapshots', methods=['POST'])
def create_snapshots():
    investments = Investment.query.all()

    if investments:
        current_time = datetime.utcnow()

        # Új sorszám létrehozása
        max_snapshot_group_id = db.session.query(db.func.max(InvestmentSnapshot.snapshot_group_id)).scalar()
        if max_snapshot_group_id is None:
            new_snapshot_group_id = 1
        else:
            new_snapshot_group_id = max_snapshot_group_id + 1

        for investment in investments:
            snapshot = InvestmentSnapshot(
                investment_id=investment.id,
                snapshot_date=current_time,
                purchase_price=investment.purchase_price,
                quantity=investment.quantity,
                current_price=investment.current_price,
                expected_interest_amount=investment.expected_interest_amount,
                snapshot_group_id=new_snapshot_group_id  # Folytonos sorszám hozzáadása
            )
            db.session.add(snapshot)
        db.session.commit()
        return jsonify({"message": "Snapshots created successfully"}), 200
    else:
        return jsonify({"message": "No investments found"}), 404

# Definiáljuk a kalkulátor útvonalát és működését.
from flask import request

@views.route('/calculator', methods=['GET', 'POST'])
@login_required
def calculator():
    result = None
    if request.method == 'POST':
        num1 = float(request.form.get('num1', 0))
        num2 = float(request.form.get('num2', 0))
        operation = request.form.get('operation')

        if operation == 'add':
            result = num1 + num2
        elif operation == 'subtract':
            result = num1 - num2
        elif operation == 'multiply':
            result = num1 * num2
        elif operation == 'divide':
            if num2 != 0:
                result = num1 / num2
            else:
                result = "A nullával való osztás nem megengedett!"

    return render_template("calculator.html", user=current_user, result=result)

# Definiáljuk az útvonalat a részvényárak lekérdezéséhez és megjelenítéséhez.

@views.route('/stock', methods=['GET', 'POST'])
def stock():
    if request.method == 'POST':
        ticker = request.form['ticker']
        start_date = request.form['start_date']
        end_date = request.form['end_date']

        data = yf.download(ticker, start=start_date, end=end_date)
        return render_template('stock_data.html', data=data.to_html(), user=current_user)

    return render_template('stock_form.html', user=current_user)

# Definiáljuk az útvonalat az eszközök létrehozásához és megjelenítéséhez.

@views.route('/create-asset', methods=['GET', 'POST'])
@login_required
def create_asset():
    assets = Asset.query.all()

    if request.method == 'POST':
        name = request.form.get('name')
        long_name = request.form.get('long_name')
        type = request.form.get('type')
        

website/templates/admin_dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <!-- Admin Dashboard title -->
    <h2>Admin Dashboard</h2>
    
    <!-- Users awaiting approval section -->
    <h3>Users awaiting approval:</h3>
    <table>
        <thead>
            <tr>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- Iterate through the users and display their emails and approval buttons -->
            {% for user in users %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>
                        <form action="{{ url_for('auth.approve_user', user_id=user.id) }}" method="post">
                            <button type="submit" class="btn btn-primary">Approve</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Investment snapshot section -->
    <h3>Investment snapshot:</h3>
    <button onclick="createSnapshots()">Create Snapshots</button>
</div>
{% endblock %}

website/templates/all_users.html
{% extends "base.html" %}

{% block title %}All Users{% endblock %}

{% block content %}
    <!-- All Users title -->
    <h3 class="text-center">All Users</h3>


    <!-- Users table -->
    <div class="table-responsive"></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Email</th>
                <th scope="col">First Name</th>
                <th scope="col">Second Name</th>
            </tr>
        </thead>
        <tbody>
             <!-- Iterate through all the users and display their information -->
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.second_name }}</td>
                    <td>
                        <!-- Edit and Delete user buttons -->
                        <a href="{{ url_for('views.edit_user', user_id=user.id) }}" class="btn btn-primary">Edit</a>
                        <a href="{{ url_for('views.delete_user', user_id=user.id) }}" class="btn btn-danger">Delete</a>
                      </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Meta címkék a karakterkódoláshoz és reszponzív nézethez -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Bootstrap és Font Awesome CSS hivatkozások -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">-->
    <!-- Dinamikus oldalcím -->
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <!-- Navigációs sáv -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="allUsers" href="{{ url_for('views.all_users') }}">Users</a>
          <a class="nav-item nav-link" id="createAsset" href="{{ url_for('views.create_asset') }}">Asset</a>
          <a class="nav-item nav-link" id="createInvestment" href="{{ url_for('views.create_investment') }}">Investment</a>
          <a class="nav-item nav-link" id="adminDashboard" href="{{ url_for('views.admin_dashboard') }}">Admin</a>
          <a class="nav-item nav-link" id="calculator" href="{{ url_for('views.calculator') }}">Calculator</a>
          <a class="nav-item nav-link" id="stock" href="{{ url_for('views.stock') }}">Stock</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
      </div>
      </div>
    </nav>

    <!-- Üzenetek megjelenítése -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <!-- Tartalom konténer -->
    <div class="container">{% block content %} {% endblock %}</div>

    <!-- JavaScript fájlok hivatkozásai -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <!-- JavaScript blokk -->
    {% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/";
        });
      }

      function createSnapshots() {
        fetch('/create_snapshots', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
          },
        })
        .then((response) => {
          if (response.ok) {
            alert('Snapshots created successfully');
          } else {
            alert('Error creating snapshots');
          }
        })
        .catch((error) => {
          console.error('Error:', error);
        });
      }
    </script>
    {% endblock %}
  </body>
</html>

website/templates/calculator.html
{% extends "base.html" %}

{% block content %}
  <h1>Calculator</h1>
    <form action="{{ url_for('views.calculator') }}" method="post">
    <input type="number" name="num1" placeholder="Első szám">
    <input type="number" name="num2" placeholder="Második szám">
    <select name="operation">
      <option value="add">Összeadás</option>
      <option value="subtract">Kivonás</option>
      <option value="multiply">Szorzás</option>
      <option value="divide">Osztás</option>
    </select>
    <button type="submit">Számol</button>
  </form>
  {% if result %}
    <h2>Eredmény: {{ result }}</h2>
  {% endif %}
{% endblock %}

website/templates/create_investment.html
{% extends "base.html" %}
{% block content %}
<style>
    /* Styling for the form */
    form {
        display: flex;
        flex-direction: column;
        width: 1350px;
        margin: 0 auto;
    }
    /* Styling for the labels */
    label {
        margin-top: 10px;
    }
    /* Styling for the button */
    button {
        margin-top: 20px;
        width: 100px;
        align-self: center;
    }
        /* Add individual column width styles */
    table {
        table-layout: fixed;
        width: 100%;
    }
    th, td {
        text-align: left;
        padding: 8px;
        overflow: hidden;
        white-space: nowrap;
    }
    th {
        text-align: center;
        white-space: normal;
        word-wrap: break-word;
    } 
    .user-col {
        width: 150px;
    }
    .asset-name-col {
        width: 150px;
    }
    .asset-type-col {
        width: 150px;
    }
    .purchase-date-col {
        width: 150px;
    }
    .purchase-price-col {
        width: 150px;
    }
    .quantity-col {
        width: 150px;
    }
    .current-price-col {
        width: 150px;
    }
    .expected-interest-col {
        width: 180px;
    }
    .interest-payment-date-col {
        width: 150px;
    }
    .maturity-date-col {
        width: 150px;
    }
    .actions-col {
        width: 180px;
    }
</style>
<div class="container">
    <!-- Investment title -->
    <h2>Investment</h2>
    <div class="container">

        <!-- Add investment form -->
        <form action="{{ url_for('views.create_investment') }}" method="post">
            <!-- Input fields for investment details -->
            <label for="asset">Asset</label>
            <select name="asset" id="asset" required>
                {% for asset in assets %}
                <option value="{{ asset.id }}">{{ asset.name }}</option>
                {% endfor %}
            </select>            
            <label for="purchaseDate">Purchase Date</label>
            <input type="date" name="purchaseDate" id="purchaseDate" required>
            <label for="purchasePrice">Purchase Price</label>
            <input type="number" step="any" name="purchasePrice" id="purchasePrice" required>
            <label for="quantity">Quantity</label>
            <input type="number" step="any" name="quantity" id="quantity" required>
            <label for="currentPrice">Current Price</label>
            <input type="number" step="any" name="currentPrice" id="currentPrice" required>
            <label for="expectedInterestAmount">Expected Interest Amount</label>
            <input type="number" step="any" name="expectedInterestAmount" id="expectedInterestAmount" required>
            <!-- Input fields for investment details -->
            <label for="user">User</label>
            <select name="user" id="user" required>
                {% for user in users %}
                <option value="{{ user.id }}">{{ user.first_name }} {{ user.second_name }}</option>
                {% endfor %}
            </select>
            <!-- Add button -->
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
        <!-- Existing investments table -->
        <h2>Existing Investments</h2>
        <table>
            <thead>
                <tr>
                    <th class="user-col">User</th>
                    <th class="asset-name-col">Asset Name</th>
                    <th class="asset-type-col">Asset Type</th>
                    <th class="purchase-date-col">Purchase Date</th>
                    <th class="purchase-price-col">Purchase Price</th>
                    <th class="quantity-col">Quantity</th>
                    <th class="current-price-col">Current Price</th>
                    <th class="expected-interest-col">Expected Interest Amount</th>
                    <th class="actions-col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <!-- Iterate through all investments and display their details in the table -->
                {% for investment in user_investments %}
    <tr>
        <td class="user-col">{{ investment.user.first_name }} {{ investment.user.second_name }}</td>
        <td class="asset-name-col">{{ investment.asset.name }}</td>
        <td class="asset-type-col">{{ investment.asset.type }}</td>
        <td class="purchase-date-col">{{ investment.purchase_date.strftime('%Y-%m-%d') }}</td>
        <td class="purchase-price-col">{{ investment.purchase_price }}</td>
        <td class="quantity-col">{{ investment.quantity }}</td>
        <td class="current-price-col">{{ investment.current_price }}</td>
        <td class="expected-interest-col">{{ investment.expected_interest_amount }}</td>
        <!-- Edit and Delete buttons for each investment -->
        <td class="action-col">
            <a href="{{ url_for('views.edit_investment', investment_id=investment.id) }}" class="btn btn-primary">Edit</a>
            <a href="{{ url_for('views.delete_investment', investment_id=investment.id) }}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
{% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

website/templates/edit_asset.html
{% extends "base.html" %}

{% block content %}
<style>
    form {
        display: flex;
        flex-direction: column;
        width: 1350px;
        margin: 0 auto;
    }
    label {
        margin-top: 10px;
    }
    button {
        margin-top: 20px;
        width: 100px;
        align-self: center;
    }
</style>
<div class="container">
    <h2>Edit Asset</h2>
    <form action="{{ url_for('views.edit_asset', asset_id=asset.id) }}" method="post">
        <label for="name">Asset Name</label>
        <input type="text" name="name" id="name" value="{{ asset.name }}" required>
        <label for="name">Long Name</label>
        <input type="text" name="long_name" id="long_name" value="{{ asset.long_name }}" required>
        <label for="type">Asset Type</label>
        <input type="text" name="type" id="type" value="{{ asset.type }}" required>
        <label for="interestPaymentDate">Interest Payment Date</label>
        <input type="date" name="interestPaymentDate" id="interestPaymentDate" value="{{ asset.interest_payment_date.strftime('%Y-%m-%d') if asset.interest_payment_date else '' }}">
        <label for="maturityDate">Maturity Date</label>
        <input type="date" name="maturityDate" id="maturityDate" value="{{ asset.maturity_date.strftime('%Y-%m-%d') if asset.maturity_date else '' }}">
        <label for="description">Description</label>
        <textarea name="description" id="description" required>{{ asset.description }}</textarea>
        <label for="location">Location</label>
        <input type="text" name="location" id="location" value="{{ asset.location }}" required>
        <label for="link">Link</label>
        <input type="text" name="link" id="link" value="{{ asset.link }}">
        <label for="costs">Costs</label>
        <input type="number" step="any" name="costs" id="costs" value="{{ asset.costs }}">
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}

website/templates/edit_investment.html
{% extends "base.html" %}

{% block content %}
<style>
    form {
        display: flex;
        flex-direction: column;
        width: 1350px;
        margin: 0 auto;
    }
    label {
        margin-top: 10px;
    }
    button {
        margin-top: 20px;
        width: 100px;
        align-self: center;
    }
</style>
    <!-- Container div -->
    <div class="container">
        <h2>Edit Investment</h2>
        <!-- Edit investment form -->
        <form action="{{ url_for('views.edit_investment', investment_id=investment.id) }}" method="post">
            <!-- Asset selection dropdown -->
            <label for="asset">Asset</label>
            <select name="asset" id="asset" required> 
                {% for asset in assets %} 
                    <option value="{{ asset.id }}" {% if asset.id == investment.asset_id %}selected{% endif %}>{{ asset.name }}</option> 
                {% endfor %} 
            </select> 
            <label for="purchaseDate">Purchase Date</label>
            <input type="date" name="purchaseDate" id="purchaseDate" value="{{ investment.purchase_date.date() }}" required>
            <label for="purchasePrice">Purchase Price</label>
            <input type="number" step="any" name="purchasePrice" id="purchasePrice" value="{{ investment.purchase_price }}" required>
            <label for="quantity">Quantity</label>
            <input type="number" step="any" name="quantity" id="quantity" value="{{ investment.quantity }}" required>
            <label for="currentPrice">Current Price</label>
            <input type="number" step="any" name="currentPrice" id="currentPrice" value="{{ investment.current_price }}" required>
            <label for="expectedInterestAmount">Expected Interest Amount</label>
            <input type="number" step="any" name="expectedInterestAmount" id="expectedInterestAmount" value="{{ investment.expected_interest_amount }}" required>
            <!-- User selection dropdown -->
            <label for="user">User</label>
            <select name="user" id="user" required> 
                {% for user in users %} 
                    <option value="{{ user.id }}" {% if user.id == investment.user_id %}selected{% endif %}>{{ user.first_name }} {{ user.second_name }}</option> 
                {% endfor %} 
            </select> 
             <!-- Update button -->           
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock %}

website/templates/password_protected.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Password Protected Page</h2>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
    <form action="{{ url_for('views.admin_dashboard') }}" method="post">
        <label for="password">Enter the password:</label>
        <input type="password" name="password" required>
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}